name: CI-CD Test on IIS (.NET Framework - QA Only)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:

  build_test:
    name: Build (.NET Framework)
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore NuGet Packages
        run: nuget restore TestProject1.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Solution (Release)
        run: msbuild TestProject1.sln /p:Configuration=Release

      - name: Publish Web App (FileSystem)
        run: msbuild TestProject1.sln /p:WebPublishMethod=FileSystem /p:PublishUrl=".\publish" /p:Configuration=Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: publish/


  deploy_qa:
    name: Deploy to QA Server (Local IIS)
    needs: build_test
    runs-on: [self-hosted, windows, x64, qa]   # Your machine's runner label
    environment:
      name: qa

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: webapp

      - name: Deploy to IIS (QA)
        shell: pwsh
        env:
          SITE_PATH: "D:\New folder"
          SITE_NAME: "CICDTestSite"
        run: |
          Import-Module WebAdministration

          Write-Host "Creating backup before deploy..."
          $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
          $backup = Join-Path (Split-Path $env:SITE_PATH) "backup-$timestamp"
          New-Item -ItemType Directory -Force -Path $backup | Out-Null
          if (Test-Path $env:SITE_PATH) {
            Copy-Item "$env:SITE_PATH\*" $backup -Recurse -Force -ErrorAction SilentlyContinue
          }

          Write-Host "Stopping IIS site $env:SITE_NAME"
          & $env:windir\system32\inetsrv\appcmd stop site "$env:SITE_NAME"

          Write-Host "Removing existing files..."
          Remove-Item "$env:SITE_PATH\*" -Recurse -Force -ErrorAction SilentlyContinue

          Write-Host "Publishing new build files..."
          Copy-Item "webapp\*" $env:SITE_PATH -Recurse -Force

          Write-Host "Starting IIS site $env:SITE_NAME"
          & $env:windir\system32\inetsrv\appcmd start site "$env:SITE_NAME"

          Write-Host "✅ Deployment to QA completed successfully!"
